"""diet notes

Revision ID: a74f38d61d82
Revises: 400d5df68e85
Create Date: 2026-10-02 15:04:33.539294
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op


revision: str = 'a74f38d61d82'
down_revision: str | None = '400d5df68e85'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_notes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_diet_notes_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_diet_notes_prescription_id_prescriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diet_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_notes'))
    )
    op.create_index(op.f('ix_diet_notes_document_id'), 'diet_notes', ['document_id'], unique=False)
    op.create_index(op.f('ix_diet_notes_prescription_id'), 'diet_notes', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_diet_notes_user_id'), 'diet_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diet_notes_user_id'), table_name='diet_notes')
    op.drop_index(op.f('ix_diet_notes_prescription_id'), table_name='diet_notes')
    op.drop_index(op.f('ix_diet_notes_document_id'), table_name='diet_notes')
    op.drop_table('diet_notes')
    # ### end Alembic commands ###
