"""extraction evidence

Revision ID: 586d1de29c85
Revises: c303047d6642
Create Date: 2026-10-03 22:16:20.556489
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '586d1de29c85'
down_revision: str | None = 'c303047d6642'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractions', 'evidence')
    # ### end Alembic commands ###
