"""dose logs

Revision ID: 315eb3883972
Revises: c44b940eeb3d
Create Date: 2026-10-02 17:50:05.187268
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '315eb3883972'
down_revision: str | None = 'c44b940eeb3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dose_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_dose_logs_medication_id_medications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dose_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dose_logs')),
    sa.UniqueConstraint('medication_id', 'due_date', 'due_time', name='uq_dose_logs_dose')
    )
    op.create_index(op.f('ix_dose_logs_medication_id'), 'dose_logs', ['medication_id'], unique=False)
    op.create_index(op.f('ix_dose_logs_user_id'), 'dose_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dose_logs_user_id'), table_name='dose_logs')
    op.drop_index(op.f('ix_dose_logs_medication_id'), table_name='dose_logs')
    op.drop_table('dose_logs')
    # ### end Alembic commands ###
