"""record source refs

Revision ID: e0a5a5117479
Revises: 586d1de29c85
Create Date: 2026-10-04 22:24:20.406112
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e0a5a5117479'
down_revision: str | None = '586d1de29c85'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_actions', sa.Column('source_ref', sa.String(length=32), nullable=True))
    op.add_column('diet_notes', sa.Column('source_ref', sa.String(length=32), nullable=True))
    op.add_column('lab_results', sa.Column('source_ref', sa.String(length=32), nullable=True))
    op.add_column('medications', sa.Column('source_ref', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'source_ref')
    op.drop_column('lab_results', 'source_ref')
    op.drop_column('diet_notes', 'source_ref')
    op.drop_column('care_actions', 'source_ref')
    # ### end Alembic commands ###
