"""medication supplies

Revision ID: 6d705d5fb324
Revises: f1b1051067ac
Create Date: 2026-10-02 21:59:23.843506
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6d705d5fb324'
down_revision: str | None = 'f1b1051067ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_supplies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('on_hand', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('units_per_dose', sa.Float(), nullable=False),
    sa.Column('low_days', sa.Integer(), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_medication_supplies_medication_id_medications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medication_supplies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_supplies')),
    sa.UniqueConstraint('medication_id', name=op.f('uq_medication_supplies_medication_id'))
    )
    op.create_index(op.f('ix_medication_supplies_user_id'), 'medication_supplies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_supplies_user_id'), table_name='medication_supplies')
    op.drop_table('medication_supplies')
    # ### end Alembic commands ###
