"""google own calendar

Revision ID: 56eda3ff9c6d
Revises: 7db8760c1a76
Create Date: 2026-10-07 12:35:51.906927
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "56eda3ff9c6d"
down_revision: str | None = "7db8760c1a76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth_connections", sa.Column("calendar_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_connections", "calendar_id")
    # ### end Alembic commands ###
