"""care links

Revision ID: 3039e41c8dd4
Revises: 6d705d5fb324
Create Date: 2026-10-03 11:36:53.476854
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3039e41c8dd4'
down_revision: str | None = '6d705d5fb324'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_links',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('caregiver_id', sa.Uuid(), nullable=True),
    sa.Column('invite_email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_hint', sa.String(length=8), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], name=op.f('fk_care_links_caregiver_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_care_links_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_care_links_token_hash'))
    )
    op.create_index('ix_care_links_caregiver_owner', 'care_links', ['caregiver_id', 'owner_id'], unique=False)
    op.create_index(op.f('ix_care_links_owner_id'), 'care_links', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_links_owner_id'), table_name='care_links')
    op.drop_index('ix_care_links_caregiver_owner', table_name='care_links')
    op.drop_table('care_links')
    # ### end Alembic commands ###
