"""visit preps

Revision ID: f1b1051067ac
Revises: 315eb3883972
Create Date: 2026-10-02 21:18:11.144537
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f1b1051067ac'
down_revision: str | None = '315eb3883972'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_preps',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('clinician', sa.String(length=120), nullable=True),
    sa.Column('since', sa.Date(), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_visit_preps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_preps'))
    )
    op.create_index(op.f('ix_visit_preps_user_id'), 'visit_preps', ['user_id'], unique=False)
    op.create_index(op.f('ix_visit_preps_visit_date'), 'visit_preps', ['visit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_preps_visit_date'), table_name='visit_preps')
    op.drop_index(op.f('ix_visit_preps_user_id'), table_name='visit_preps')
    op.drop_table('visit_preps')
    # ### end Alembic commands ###
