"""caregiver dose alerts

Revision ID: 7db8760c1a76
Revises: e0a5a5117479
Create Date: 2026-10-04 23:22:11.761639
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7db8760c1a76'
down_revision: str | None = 'e0a5a5117479'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_reminder_logs',
    sa.Column('care_link_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.String(length=5), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['care_link_id'], ['care_links.id'], name=op.f('fk_caregiver_reminder_logs_care_link_id_care_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_caregiver_reminder_logs_medication_id_medications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caregiver_reminder_logs')),
    sa.UniqueConstraint('care_link_id', 'medication_id', 'due_date', 'due_time', name='uq_caregiver_reminder')
    )
    op.create_index(op.f('ix_caregiver_reminder_logs_care_link_id'), 'caregiver_reminder_logs', ['care_link_id'], unique=False)
    op.add_column('care_links', sa.Column('alert_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_links', 'alert_minutes')
    op.drop_index(op.f('ix_caregiver_reminder_logs_care_link_id'), table_name='caregiver_reminder_logs')
    op.drop_table('caregiver_reminder_logs')
    # ### end Alembic commands ###
