"""share links

Revision ID: 0d786ae0d29b
Revises: 981a1c5fdf9c
Create Date: 2026-10-02 00:40:22.535873
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op


revision: str = '0d786ae0d29b'
down_revision: str | None = '981a1c5fdf9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_hint', sa.String(length=8), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_share_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_share_links_token_hash'))
    )
    op.create_index(op.f('ix_share_links_user_id'), 'share_links', ['user_id'], unique=False)
    op.create_table('share_link_items',
    sa.Column('share_link_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], name=op.f('fk_share_link_items_share_link_id_share_links'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_link_items')),
    sa.UniqueConstraint('share_link_id', 'item_type', 'item_id', name='uq_share_item')
    )
    op.create_index(op.f('ix_share_link_items_share_link_id'), 'share_link_items', ['share_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_link_items_share_link_id'), table_name='share_link_items')
    op.drop_table('share_link_items')
    op.drop_index(op.f('ix_share_links_user_id'), table_name='share_links')
    op.drop_table('share_links')
    # ### end Alembic commands ###
